services:
  builder:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"